### ISSUE TITLE
Unreferenced type included in introspection

### ISSUE THREAD

**Issue by breyed** [EntityGraphQL/EntityGraphQL#120]
When a field is removed, the type of that field is still exposed during introspection.

For example, use [GraphQL Code Generator](https://www.graphql-code-generator.com/) to generate code with entities:

``` c#
public class TypeA {
   public int Id { get; set; }
   public TypeB B { get; set; }
}

public class TypeB {
   public int Id { get; set; }
}
```

Remove TypeA.B with:

``` c#
provider.UpdateType<TypeA>(t => {
	t.RemoveField(e => e.B);
});
```

The type TypeB is still included in the generated code, even though it's never referenced.

**Comment by lukemurray** [comment]
The Type might be used by other fields. So removing a single field, just removes the field against that's fields type.

If you want to remove a type and every field that uses that type you can use `provider.RemoveTypeAndAllFields<TypeB>()`

If will remove the type from the schema and any field in the schema that returns that type.

**Comment by breyed** [comment]
I tried using `RemoveTypeAndAllFields` to remove my type, but it didn't work. In my case, the undesired type is called `ApplicationUser`, which derived from `IdentityUser` as described [here](https://github.com/EntityGraphQL/EntityGraphQL/issues/119#issuecomment-1147365248).

I used this code:
``` c#
provider.RemoveTypeAndAllFields<ApplicationUser>();
```

At app startup, it caused this exception:
> Unhandled exception. EntityGraphQL.Compiler.EntityGraphQLCompilerException: No schema type found for dotnet type DateTimeOffset. Make sure you add it or add a type mapping

Here's the stack trace:
```
   at EntityGraphQL.Schema.SchemaProvider`1.GetSchemaType(Type dotnetType, QueryRequestContext requestContext)
   at EntityGraphQL.Schema.SchemaBuilder.<>c__DisplayClass10_0.<ProcessFieldOrProperty>b__0()
   at EntityGraphQL.Schema.SchemaProvider`1.RemoveFieldsOfType(String schemaType, ISchemaType contextType)
   at EntityGraphQL.Schema.SchemaProvider`1.RemoveTypeAndAllFields(String typeName)
   at EntityGraphQL.Schema.SchemaProvider`1.RemoveTypeAndAllFields[TSchemaType]()
   at Watertight.Website.Data.GraphQLContext.ConfigureSchema(SchemaProvider`1 provider) in C:\Users\Brey\Code\Watertight\Website\Data\GraphQLContext.cs:line 44
   at EntityGraphQL.AspNet.EntityGraphQLAspNetServiceCollectionExtensions.AddGraphQLSchema[TSchemaContext](IServiceCollection serviceCollection, Action`1 configure)
   at EntityGraphQL.AspNet.EntityGraphQLAspNetServiceCollectionExtensions.AddGraphQLSchema[TSchemaContext](IServiceCollection serviceCollection, Action`1 configure)
```

Additionally, while it is useful sometimes to remove a type and all places it's referenced, the other approach of removing a field and having types no longer unreferenced be excluded is also a logical approach to configuration. It would be great to support both approaches.

**Comment by lukemurray** [comment]
Agree when removing a field it would be nice to (likely default) be able to clean up the type if it is unused - from a usage/API point of view. Functionally `RemoveTypeAndAllFields` should do the same thing - remove that 1 field and the type.

I need to dig into this some more to look what is happening. I am guessing that `provider.RemoveTypeAndAllFields<IdentityUser>();` as well might help.

Likely need to search deeper on types in `RemoveTypeAndAllFields`. Hopefully be able to have a deeper look this weekend.
