### ISSUE TITLE
Support DateTimeOffset type

### ISSUE THREAD

**Issue by anatolii-bohdanov** [EntityGraphQL/EntityGraphQL#190]
Good day!

I am receiving the next error while using the [getting started guide](https://entitygraphql.github.io/docs/getting-started#create-the-api)

```
EntityGraphQL.Compiler.EntityGraphQLCompilerException
  HResult=0x80131500
  Message=No schema type found for dotnet type DateTimeOffset. Make sure you add it or add a type mapping
  Source=EntityGraphQL
  StackTrace:
   at EntityGraphQL.Schema.SchemaProvider`1.GetSchemaType(Type dotnetType, QueryRequestContext requestContext)
   at EntityGraphQL.Schema.SchemaBuilder.CacheType(Type propType, ISchemaProvider schema, SchemaBuilderOptions options, Boolean isInputType)
   at EntityGraphQL.Schema.SchemaBuilder.<ProcessFieldOrProperty>d__6.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at EntityGraphQL.Schema.SchemaBuilder.GetFieldsFromObject(Type type, ISchemaProvider schema, SchemaBuilderOptions options, Boolean isInputType)
   at EntityGraphQL.Schema.SchemaBuilder.CacheType(Type propType, ISchemaProvider schema, SchemaBuilderOptions options, Boolean isInputType)
   at EntityGraphQL.Schema.SchemaBuilder.<ProcessFieldOrProperty>d__6.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at EntityGraphQL.Schema.SchemaBuilder.GetFieldsFromObject(Type type, ISchemaProvider schema, SchemaBuilderOptions options, Boolean isInputType)
   at EntityGraphQL.Schema.SchemaBuilder.CacheType(Type propType, ISchemaProvider schema, SchemaBuilderOptions options, Boolean isInputType)
   at EntityGraphQL.Schema.SchemaBuilder.<ProcessFieldOrProperty>d__6.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at EntityGraphQL.Schema.SchemaBuilder.GetFieldsFromObject(Type type, ISchemaProvider schema, SchemaBuilderOptions options, Boolean isInputType)
   at EntityGraphQL.Schema.SchemaBuilder.CacheType(Type propType, ISchemaProvider schema, SchemaBuilderOptions options, Boolean isInputType)
   at EntityGraphQL.Schema.SchemaBuilder.<ProcessFieldOrProperty>d__6.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at EntityGraphQL.Schema.SchemaBuilder.GetFieldsFromObject(Type type, ISchemaProvider schema, SchemaBuilderOptions options, Boolean isInputType)
   at EntityGraphQL.Schema.SchemaBuilder.FromObject[TContextType](SchemaProvider`1 schema, SchemaBuilderOptions options)
   at EntityGraphQL.Schema.SchemaProvider`1.PopulateFromContext(SchemaBuilderOptions options)
   at EntityGraphQL.AspNet.EntityGraphQLAspNetServiceCollectionExtensions.AddGraphQLSchema[TSchemaContext](IServiceCollection serviceCollection, Action`1 configure)
   at EntityGraphQL.AspNet.EntityGraphQLAspNetServiceCollectionExtensions.AddGraphQLSchema[TSchemaContext](IServiceCollection serviceCollection, Action`1 configure)
   at Project.WebApi.Startup.ConfigureServices(IServiceCollection services) in C:\s\Project\src\api\src\Project.WebApi\Startup.cs:line 49
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Project.WebApi.Program.Main(String[] args) in C:\s\Project\src\api\src\Project.WebApi\Program.cs:line 11

```

**Comment by lukemurray** [comment]
I think you hit this issue https://github.com/EntityGraphQL/EntityGraphQL/issues/119

Basically `DateTimeOffset` is used somewhere in you object graph. EntityGraphQL sees it but doesn't know what to do with it.

You can map it to `Date`

```
services.AddGraphQLSchema<DemoContext>(options =>
{
    options.PreBuildSchemaFromContext = (schema) =>
    {
        schema.AddTypeMapping<DateTimeOffset>("Date");
    };
});
```

I just realised why it is not auto being added with the option `AutoCreateNewComplexTypes` and that is because it is a `struct`.

For now you'll have to let EntityGraphQL know what you want to do with it. You can also register it as a separate scalar type too.

```
services.AddGraphQLSchema<DemoContext>(options =>
{
    options.PreBuildSchemaFromContext = (schema) =>
    {
        schema.AddScalarType<DateTimeOffset>("DateTimeOffset", "Type representing a DateTimeOffset");
    };
});
```

**Comment by anatolii-bohdanov** [comment]
Thanks, @lukemurray. I will try it.

**Comment by lukemurray** [comment]
Now a default scalar in next release
