### ISSUE TITLE
3.0.3 - EntityGraphQLCompilerException: Names must only contain [_a-zA-Z0-9] but 'Byte[]' does not.

### ISSUE THREAD

**Issue by bzbetty** [EntityGraphQL/EntityGraphQL#194]
```
   at EntityGraphQL.Schema.BaseSchemaTypeWithFields`1..ctor(ISchemaProvider schema, String name, String description, RequiredAuthorization requiredAuthorization)
   at EntityGraphQL.Schema.SchemaType`1..ctor(ISchemaProvider schema, Type dotnetType, String name, String description, RequiredAuthorization requiredAuthorization, GqlTypeEnum gqlType, String baseType)
   at EntityGraphQL.Schema.SchemaType`1..ctor(ISchemaProvider schema, String name, String description, RequiredAuthorization requiredAuthorization, GqlTypeEnum gqlType, String baseType)
   at EntityGraphQL.Schema.SchemaProvider`1.AddType[TBaseType](String name, String description)
```

Guessing this is a recent change to scalar types?

**Comment by lukemurray** [comment]
Yes. As that it technically an invalid graphql name. So depending on how the tools strictly follow the spec you will get errors
________________________________
From: bzbetty ***@***.***>
Sent: Friday, August 5, 2022 12:53:22 PM
To: EntityGraphQL/EntityGraphQL ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EntityGraphQL/EntityGraphQL] 3.0.3 - EntityGraphQLCompilerException: Names must only contain [_a-zA-Z0-9] but 'Byte[]' does not. (Issue #194)


   at EntityGraphQL.Schema.BaseSchemaTypeWithFields`1..ctor(ISchemaProvider schema, String name, String description, RequiredAuthorization requiredAuthorization)
   at EntityGraphQL.Schema.SchemaType`1..ctor(ISchemaProvider schema, Type dotnetType, String name, String description, RequiredAuthorization requiredAuthorization, GqlTypeEnum gqlType, String baseType)
   at EntityGraphQL.Schema.SchemaType`1..ctor(ISchemaProvider schema, String name, String description, RequiredAuthorization requiredAuthorization, GqlTypeEnum gqlType, String baseType)
   at EntityGraphQL.Schema.SchemaProvider`1.AddType[TBaseType](String name, String description)


Guessing this is a recent change to scalar types?

**Comment by bzbetty** [comment]
Currently working around the issue by removing byte[] scalar since i don't use it.
`schemaProvider.RemoveType<byte[]>();`

**Comment by bzbetty** [comment]
Correction, fixing it by adding a type since it's currently a custom mapping

schemaProvider.AddType<byte[]>("byteArray", "");

**Comment by lukemurray** [comment]
Seems `HasType` is not checking mappings. So Schema Builder tries to add it!
