### ISSUE TITLE
Union error: "variable '....' of type '....' referenced from scope '', but it is not defined"

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [EntityGraphQL/EntityGraphQL#264]
We have some code that uses unions, like so:

```c#
public interface IUser { }

public class Employee : IUser
{
    public string Name { get; set; }
}

public class UsersContext : IUsersContext
{
    public List<IUser> Users { get; set; } = new()
    {
        new Employee
        {
            Name = "test user"
        }
    };
}

public interface IUsersContext
{
    public List<IUser> Users { get; }
}

public class Program
{
    public static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);

        builder.Services.AddCors();
        builder.Services.AddTransient<IUsersContext, UsersContext>();
        builder.Services.AddGraphQLSchema<IUsersContext>(options =>
        {
            options.AutoBuildSchemaFromContext = false;

            options.ConfigureSchema = (schema) =>
            {
                schema.AddUnion<IUser>("user", null);
                schema.Type<IUser>().AddAllPossibleTypes();

                schema.UpdateQuery(queryType =>
                {
                    queryType.ReplaceField(
                        "users",
                        db => db.Users,
                        null
                    );
                });
            };
        });

        var app = builder.Build();
        app.UseHttpsRedirection();
        app.UseRouting();
        app.UseCors(builder =>
        {
            builder
            .WithOrigins("*")
            .WithMethods("POST")
            .AllowAnyHeader();
        });
        app.UseEndpoints(endpoints => endpoints.MapGraphQL<IUsersContext>());
        app.Run();
    }
}
```

When I execute this query:
```
{
   users
   {
      ... on Employee
      {
         name
      }
   }
}
```

I get this exception:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=variable 'p_Employee' of type 'Example.Employee' referenced from scope '', but it is not defined
  Source=System.Linq.Expressions
  StackTrace:
   at System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(ParameterExpression node)
   at System.Linq.Expressions.ParameterExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.MemberExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.LambdaExpression.Compile()
   at EntityGraphQL.Compiler.ExecutableGraphQLStatement.<ExecuteExpressionAsync>d__32.MoveNext() in EntityGraphQL\Compiler\GqlNodes\ExecutableGraphQLStatement.cs:line 244
```

The error message appears to be similar to #239, but the repro steps are different.

This was tested with commit 099aad8cdb3b6c8f4dbc4b17b4727ba408dfb0f3

**Comment by bzbetty** [comment]
i have a feeling the implementation doesn't like only querying for a single type, in the method MakeSelectWithDynamicType i defaulted back to the old code is validTypes < 2.  Was for a mix of performance/safety reasons but I clearly missed this case.

Can you try add a second fragment type ?

**Comment by Bosch-Eli-Black** [comment]
@bzbetty Oooo, indeed, adding a second fragment type to the query makes the error go away! 🙂

**Comment by bzbetty** [comment]
what happens if you also ask for typename?

{ __typename users { ... on Employee { name } ... on Owner { id } } }

**Comment by bzbetty** [comment]
Have a look at TestAutoUnion seems to be a basic working sample? 
I thought I'd used Unions in my codebase somehwere, i'll have a dig tomorrow.

**Comment by bzbetty** [comment]
Actually is this the same field vs property serialization issue you had in #263 ?

**Comment by lukemurray** [comment]
Shouldn't be the serialisation issue if running the above code as that is using the `MapGraphQL` extensions which sets that up.

**Comment by Bosch-Eli-Black** [comment]
@bzbetty  I thought this might be a field serialization issue, too (since indeed, I just messed that up, haha 😆), but as @lukemurray says, in this example, I'm using `AddGraphQLSchema()`.

**Comment by bzbetty** [comment]
What version are you running against? if I use your sample app against 4.0.1 i get quiet a different error

![image](https://user-images.githubusercontent.com/533131/194269321-632a3d50-e9d8-4012-b588-337bf74b4913.png)

**Comment by Bosch-Eli-Black** [comment]
@bzbetty  I'm running against commit https://github.com/EntityGraphQL/EntityGraphQL/commit/099aad8cdb3b6c8f4dbc4b17b4727ba408dfb0f3 🙂

**Comment by bzbetty** [comment]
oh interesting, my error seems to be due to not wrapping the sample app in a namespace - that's really confusing!

**Comment by bzbetty** [comment]
If I do the following instead of passing the query via http it seems to return the value correctly.


```
                    var gql = new GraphQLCompiler(schema).Compile(@"
query {
   users {
      __typename
     ... on Employee { name },
    ... on Owner { id }
   }
}");
                    var context = new UsersContext();

                    var qr = gql.ExecuteQuery(context, null, null);
                    int i = 0;
```

**Comment by bzbetty** [comment]
with a breakpoint in DefaultGraphQLResponseSerializer i can confirm the data is on the object, it's just not serialized for some reason.

**Comment by bzbetty** [comment]
potentially related https://github.com/dotnet/runtime/issues/31742

**Comment by bzbetty** [comment]
also this https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism?pivots=dotnet-6-0 - although I'm not seeing a fix

**Comment by Bosch-Eli-Black** [comment]
@bzbetty Very interesting... and unexpected! 🙂

I guess in our case, the solution is simple: Use the Newtonsoft serializer, which is actually what we're using anyway... I just used the System.Json serializer in the example, since that lead to a shorter repro.

I does look like .NET 7 supports polymorphic serialization, but... ya... that'd required apps to be running .NET 7: https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/polymorphism?pivots=dotnet-7-0

It look like we uncovered three bugs within this thread, haha.

**Comment by Bosch-Eli-Black** [comment]
BTW, I can confirm that this works fine when using the Newtonsoft serializer 🙂

**Comment by lukemurray** [comment]
@Bosch-Eli-Black would you mind double checking against the master branch? Want to make sure there is not an edge case we have missed. Thanks

**Comment by Bosch-Eli-Black** [comment]
@lukemurray I'm afraid that made it a bit worse, haha 😄

**Code**
```c#
using EntityGraphQL.AspNet;

namespace Example;

public interface IUser { }

public class Employee : IUser
{
    public string Name { get; set; }
}

public class Owner : IUser
{
    public string Id { get; set; }
}

public class UsersContext : IUsersContext
{
    public List<IUser> Users { get; set; } = new()
    {
        new Employee
        {
            Name = "test employee"
        },
        new Owner
        {
            Id = "1111"
        }
    };
}

public interface IUsersContext
{
    public List<IUser> Users { get; }
}

public class Program
{
    public static void Main(string[] args)
    {
        var builder = WebApplication.CreateBuilder(args);

        builder.Services.AddCors();
        builder.Services.AddTransient<IUsersContext, UsersContext>();
        builder.Services.AddGraphQLSchema<IUsersContext>(options =>
        {
            options.AutoBuildSchemaFromContext = false;

            options.ConfigureSchema = (schema) =>
            {
                schema.AddUnion<IUser>("User", null);
                schema.Type<IUser>().AddAllPossibleTypes();

                schema.UpdateQuery(queryType =>
                {
                    queryType.ReplaceField(
                        "users",
                        db => db.Users,
                        null
                    );
                });
            };
        });

        var app = builder.Build();
        app.UseHttpsRedirection();
        app.UseRouting();
        app.UseCors(builder =>
        {
            builder
            .WithOrigins("*")
            .WithMethods("POST")
            .AllowAnyHeader();
        });
        app.UseEndpoints(endpoints => endpoints.MapGraphQL<IUsersContext>());
        app.Run();
    }
}
```

**Query**
```
{ users { __typename, ... on Employee { name } ... on Owner { id } } }
```

**Result**

```json
[
    {
        "key": "data",
        "value": [
            {
                "key": "users",
                "value": [
                    {},
                    {}
                ]
            }
        ]
    }
]
```

Tested with d65435fcfae85ac931f3f73b9f894fe0138dee3d

**Comment by bzbetty** [comment]
PR should now return

```
{
  "data": {
    "users": [
      {
        "name": "test employee",
        "__typename": "Employee"
      },
      {
        "id": "1111",
        "__typename": "Owner"
      }
    ]
  }
}
```

**Comment by Bosch-Eli-Black** [comment]
@bzbetty Thanks!

Will test tomorrow, God willing 🙂

**Comment by Bosch-Eli-Black** [comment]
@bzbetty and @lukemurray It works! Thank you! ^_^

I've confirmed that both bugs that were discovered in this issue have been fixed 🙂

* https://github.com/EntityGraphQL/EntityGraphQL/issues/264#issue-1397293409
* https://github.com/EntityGraphQL/EntityGraphQL/issues/264#issuecomment-1275635180

Thanks again! 🙂
