### ISSUE TITLE
Invalid expression on union types

### ISSUE THREAD

**Issue by Pankraty** [EntityGraphQL/EntityGraphQL#361]
I am trying to add GraphQL API over entities with a generic property, and get an exception on query execution. I've managed to create a short reproduction case but was not able  to figure out how to properly fix this. I'll keep trying but maybe you can give a hint on how to find the problem? Or, maybe I should reconsider the whole approach as it can't possibly work this way?

Here is the branch with a failing test https://github.com/EntityGraphQL/EntityGraphQL/compare/master...Pankraty:EntityGraphQL:union-types-exception

The test
```
        [Fact]
        public void TestAutoUnion_InterfaceTypedField()
        {
            var schema = SchemaBuilder.FromObject<TestUnionDataContext2>(new SchemaBuilderOptions { AutoCreateInterfaceTypes = true });
            Assert.True(schema.HasType(typeof(IAnimal)));
            Assert.True(schema.GetSchemaType(typeof(IAnimal), null).GqlType == GqlTypes.Union);

            schema.Type<IAnimal>().AddPossibleType<Dog>();
            schema.Type<IAnimal>().AddPossibleType<Cat>();
            Assert.True(schema.GetSchemaType(typeof(Cat), null).GqlType == GqlTypes.QueryObject);
            Assert.True(schema.GetSchemaType(typeof(Dog), null).GqlType == GqlTypes.QueryObject);

            var gql = new GraphQLCompiler(schema).Compile("""
                query {
                    petOwners {
                        favoritePet
                        {
                            __typename
                            ... on Cat {
                               lives
                            }
                            ... on Dog {
                               hasBone
                            }
                        }
                    }
                }
                """);
            var context = new TestUnionDataContext2();
            context.PetOwners.Add(new() { Id = 1, FavoritePet = new Dog() { Name = "steve", HasBone = true } });
            context.PetOwners.Add(new() { Id = 2, FavoritePet = new Cat() { Name = "george", Lives = 9 } });

            var qr = gql.ExecuteQuery(context, null, null);
            dynamic petOwners = qr.Data["petOwners"];

            Assert.Equal(2, petOwners.Count);
            Assert.Equal("Dog", petOwners[0].favoritePet.__typename);
            //Assert.Equal("steve", petOwners[0].favoritePet.name);
            Assert.True(petOwners[0].favoritePet.hasBone);
            Assert.Equal("Cat", petOwners[1].favoritePet.__typename);
            //Assert.Equal("george", petOwners[1].favoritePet.name);
            Assert.Equal(9, petOwners[1].favoritePet.lives);
        }
```

The data definition
```

    public class TestUnionDataContext2
    {
        public List<PetOwner> PetOwners { get; set; } = new List<PetOwner>();
    }

    public class PetOwner
    {
        public int Id { get; set; }

        public IAnimal FavoritePet { get; set; }
    }
```

The exception
```
EntityGraphQL.EntityGraphQLFieldException: Exception of type 'EntityGraphQL.EntityGraphQLFieldException' was thrown.
 ---> System.InvalidOperationException: variable 'p_Cat' of type 'EntityGraphQL.Tests.Cat' referenced from scope '', but it is not defined
   at System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(ParameterExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMember(MemberExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitConditional(ConditionalExpression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at EntityGraphQL.Compiler.ExecutableGraphQLStatement.ExecuteExpressionAsync(Expression expression, Object context, ParameterExpression contextParam, IServiceProvider serviceProvider, ParameterReplacer replacer, ExecutionOptions options, CompileContext compileContext, BaseGraphQLField node, Boolean isFinal) in D:\opensource\EntityGraphQL\src\EntityGraphQL\Compiler\GqlNodes\ExecutableGraphQLStatement.cs:line 294
   at EntityGraphQL.Compiler.ExecutableGraphQLStatement.CompileAndExecuteNodeAsync(CompileContext compileContext, Object context, IServiceProvider serviceProvider, List`1 fragments, BaseGraphQLField node, ExecutionOptions options, Object docVariables) in D:\opensource\EntityGraphQL\src\EntityGraphQL\Compiler\GqlNodes\ExecutableGraphQLStatement.cs:line 204
   at EntityGraphQL.Compiler.ExecutableGraphQLStatement.ExecuteAsync[TContext](TContext context, IServiceProvider serviceProvider, List`1 fragments, Func`2 fieldNamer, ExecutionOptions options, QueryVariables variables) in D:\opensource\EntityGraphQL\src\EntityGraphQL\Compiler\GqlNodes\ExecutableGraphQLStatement.cs:line 86
   --- End of inner exception stack trace ---
   at EntityGraphQL.Compiler.ExecutableGraphQLStatement.ExecuteAsync[TContext](TContext context, IServiceProvider serviceProvider, List`1 fragments, Func`2 fieldNamer, ExecutionOptions options, QueryVariables variables) in D:\opensource\EntityGraphQL\src\EntityGraphQL\Compiler\GqlNodes\ExecutableGraphQLStatement.cs:line 108
   at EntityGraphQL.Compiler.GraphQLDocument.ExecuteQueryAsync[TContext](TContext overwriteContext, IServiceProvider serviceProvider, QueryVariables variables, String operationName, ExecutionOptions options) in D:\opensource\EntityGraphQL\src\EntityGraphQL\Compiler\GqlNodes\GraphQLDocument.cs:line 90
   at EntityGraphQL.Compiler.GraphQLDocument.ExecuteQuery[TContext](TContext context, IServiceProvider services, QueryVariables variables, String operationName, ExecutionOptions options) in D:\opensource\EntityGraphQL\src\EntityGraphQL\Compiler\GqlNodes\GraphQLDocument.cs:line 63
   at EntityGraphQL.Tests.UnionTests.TestAutoUnion_InterfaceTypedField() in D:\opensource\EntityGraphQL\src\tests\EntityGraphQL.Tests\QueryTests\UnionTests.cs:line 249
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

Another problem that I anticipate after fixing this one is that if add the `name` property on both `Cat` and `Dog` then I have `System.ArgumentException`: "An item with the same key has already been added. Key: name"

```
query {
    petOwners {
        favoritePet
        {
            __typename
            ... on Cat {
               lives
               name
            }
            ... on Dog {
               hasBone
               name
            }
        }
    }
}
```
Should it not merge the two "names" into one property?

**Comment by lukemurray** [comment]
Thanks. Push a fix that fixes both issues you describe. Let me know if you encounter any other cases.
